ci: Propagate errorlevel/exitcode from test in DOS VM to step script

diff --git a/.github/workflows/02-pr-checks.yml b/.github/workflows/02-pr-checks.yml
--- a/.github/workflows/02-pr-checks.yml
+++ b/.github/workflows/02-pr-checks.yml
@@ -61,10 +61,11 @@ jobs:
           echo "ren dos32a.exe dos4gw.exe" >> CICD_DOS.BAT
           echo "ECHO Current BLASTER variable: %BLASTER%" >> CICD_DOS.BAT
           echo "stp32 dtmf_src.wav a32sbdg.dll" >> CICD_DOS.BAT
-          echo "ECHO %ERRORLEVEL% > EXITCODE.TXT" >> CICD_DOS.BAT
+          echo "ECHO %ERRORLEVEL% > exitcode.txt" >> CICD_DOS.BAT
           echo "ECHO Result exit code of test command:" >> CICD_DOS.BAT
-          echo "type EXITCODE.TXT" >> CICD_DOS.BAT
+          echo "type exitcode.txt" >> CICD_DOS.BAT
           cp -f test/run_cicd_dos.sh /usr/local/bin/
           chmod +x /usr/local/bin/run_cicd_dos.sh
           /usr/local/bin/run_cicd_dos.sh
-          ls -lh
+          # Propagate error code from DOS test or exit with error code 254 if the exit code file is missing
+          exit $(cat test/exitcode.txt || echo 254)
